In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [16]:
obj = {'Class' : ['A','B','C','D','A','C','G']}

df = pd.DataFrame(obj)
df

Class
0     A
1     B
2     C
3     D
4     A
5     C
6     G

In [7]:
encoder = LabelEncoder()
df['Class'] = encoder.fit_transform(df['Class'])
df

print(encoder.inverse_transform(df['Class']))

[0 1 2 3 0 2 4]


In [17]:
# numpy select = Label encoding
conditionlist = [
    (df['Class'] == 'A'),
    (df['Class'] == 'B'),
    (df['Class'] == 'C'),
    (df['Class'] == 'D'),
    (df['Class'] == 'G'),
]

choicelist = list(range(5))

np.select(condlist=conditionlist , choicelist = choicelist)


array([0, 1, 2, 3, 0, 2, 4])

In [18]:
df['Class'].map(arg = {'A':0 , 'B':1 , 'C':2 , 'D':4 , 'G':5})

0    0
1    1
2    2
3    4
4    0
5    2
6    5
Name: Class, dtype: int64

In [15]:
df['Class']

0    0
1    1
2    2
3    3
4    0
5    2
6    4
Name: Class, dtype: int64

In [20]:
## 원핫 인코딩

from sklearn.preprocessing import OneHotEncoder

obj = {'Class' : ['A','B','C','D','A','C','G','E','F']}

df = pd.DataFrame(obj)
df

Class
0     A
1     B
2     C
3     D
4     A
5     C
6     G
7     E
8     F

In [37]:
#
label_encoder = LabelEncoder()
label_encoder.fit(df['Class'])

labels = label_encoder.transform(df['Class']).reshape(-1,1)

on_encoder = OneHotEncoder(sparse = False)
on_labels = encoder.fit_transform(labels)

In [38]:
on_labels

<9x7 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [39]:
pd.get_dummies(df['Class'])

A  B  C  D  E  F  G
0  1  0  0  0  0  0  0
1  0  1  0  0  0  0  0
2  0  0  1  0  0  0  0
3  0  0  0  1  0  0  0
4  1  0  0  0  0  0  0
5  0  0  1  0  0  0  0
6  0  0  0  0  0  0  1
7  0  0  0  0  1  0  0
8  0  0  0  0  0  1  0

In [42]:
## 실습
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

obj = {
    'student_id' :['s1','s2','s3','s4','s5','s6'],
    'score' : [55,90,85,71,63,99],
}

df = pd.DataFrame(obj)

In [43]:
df['grade'] = pd.cut(df['score'],
                     bins = [0,60,70,80,90,100],# n+1
                     labels = ['가','양','미','우','수'])


In [44]:
df['grade']

0    가
1    우
2    우
3    미
4    양
5    수
Name: grade, dtype: category
Categories (5, object): ['가' < '양' < '미' < '우' < '수']

In [45]:
lb_encoder = LabelEncoder()
lb_encoder.fit(df['grade'])
lb_labels = lb_encoder.transform(df['grade'])

print(lb_labels)

[0 4 4 1 3 2]


In [48]:
print(lb_encoder.classes_)

['가' '미' '수' '양' '우']


In [49]:
lb_labels_2d = lb_labels.reshape(-1,1)

In [50]:
oh_encoder = OneHotEncoder(sparse = False)

In [51]:
oh_encoder.fit(lb_labels_2d)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [52]:
oh_labels = oh_encoder.transform(lb_labels_2d)

In [53]:
oh_labels

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])