In [1]:
import numpy as np

In [2]:
arr_1d = np.arange(8)

In [3]:
# reshape 은 바꾼 모양의 사이즈와 바뀌기 전 사이즈가 같아야 한다.
arr_1d_re = arr_1d.reshape((2,4))

In [4]:
arr_1d_re

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
arr_1d_re2 = arr_1d.reshape(4,2)

In [6]:
arr_1d_re2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [7]:
## reshape 응용
arr1 = np.arange(9).reshape(3,3)

In [8]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
## 3차원 reshape
arr2 = np.arange(12).reshape(3,2,2)

In [10]:
arr2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [11]:
arr3 = np.arange(0,100,3)

In [12]:
arr3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# 평균 반환
np.mean(arr3)

49.5

In [16]:
# 분산 반환
np.var(arr3)

866.25

In [17]:
np.min(arr3)

0

In [18]:
np.max(arr3)

99

In [19]:
np.argmin(arr3)

0

In [20]:
np.argmax(arr3)

33

In [21]:
np.quantile(arr3 , 0.25)

24.75

In [22]:
np.quantile(arr3 , 0.75)

74.25