In [36]:
#import
import numpy as np

In [37]:
np1 = np.array([1,2,3,4,5])

for i in range(len(np1)):
    print(np1[i])
for j in range(-1,-6 ,-1):
    print(np1[j])
'''
index = 0 = -len(np)
 1 = -(len(np)-1)
 2 = -(len(np)-2)
 3 = -(len(np)-3)
 4 = -(len(np)-4)
'''

1
2
3
4
5
5
4
3
2
1


'\nindex = 0 = -len(np)\n 1 = -(len(np)-1)\n 2 = -(len(np)-2)\n 3 = -(len(np)-3)\n 4 = -(len(np)-4)\n'

## 2d- array

In [38]:
np2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

In [39]:
print(np2[0,0]) # numpy[행 , 열]

1


In [40]:
print(np2[-4,-3])

1


In [41]:
print(np2[2,1])

8


In [42]:
print(np2[-2,-2])

8


In [43]:
# 변형 행은 양수로 열은 음수로
print(np2[0,-1])

3


In [44]:
print(np2[-1,0])

10


## Slice

In [45]:
arr_1d = np.array([1,2,3,4,5])

print(arr_1d[0:2]) # 0 ~ 2-1 까지
print(arr_1d[:2]) # 1 이하인 모든 데이터
print(arr_1d[1:4])
print(arr_1d[-4:-1])

[1 2]
[1 2]
[2 3 4]
[2 3 4]


In [46]:
print(arr_1d[3:5])
print(arr_1d[3:])
print(arr_1d[-2:])

[4 5]
[4 5]
[4 5]


In [47]:
## 2d array slice

arr_2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],])

print(arr_2d[0:4 , 1]) ## [행시작 : 행 끝 , 열 시작:열끝]
print(arr_2d[: , 1])
print(arr_2d[:4,1])
print(arr_2d[1:3 , 1:3])
print(arr_2d[:-1 , :-1])

[ 2  6 10 14]
[ 2  6 10 14]
[ 2  6 10 14]
[[ 6  7]
 [10 11]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


## ndarray 원소별 연산

In [49]:
np1 = np.array([0,-1,5,-4,-7,9,10])

## abs = 절대값 연산
print(np.abs(np1))

## fabs = 절대값 연산인데 abs 보다 빠름
print(np.fabs(np1))

## sqrt = 제곱근을 반환 , 음수는 nan 반환
print(np.sqrt(np1))

## square = 제곱을 반환
print(np.square(np1))

## exp = 밑이 e 인 지수 함수 값을 반환
print(np.exp(np1))

## log = 밑이 자연로그 값을 반환
print(np.log(np1))

## log10 상용 로그 값 반환
print(np.log10(np1))

## 원소별 부호 값을 반환
print(np.sign(np1))

[ 0  1  5  4  7  9 10]
[ 0.  1.  5.  4.  7.  9. 10.]
[0.                nan 2.23606798        nan        nan 3.
 3.16227766]
[  0   1  25  16  49  81 100]
[1.00000000e+00 3.67879441e-01 1.48413159e+02 1.83156389e-02
 9.11881966e-04 8.10308393e+03 2.20264658e+04]
[      -inf        nan 1.60943791        nan        nan 2.19722458
 2.30258509]
[      -inf        nan 0.69897           nan        nan 0.95424251
 1.        ]
[ 0 -1  1 -1 -1  1  1]


<ipython-input-49-08a00e1ec92f>:10: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))
<ipython-input-49-08a00e1ec92f>:19: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
<ipython-input-49-08a00e1ec92f>:19: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))
<ipython-input-49-08a00e1ec92f>:22: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(np1))
<ipython-input-49-08a00e1ec92f>:22: RuntimeWarning: invalid value encountered in log10
  print(np.log10(np1))


## 소수점 처리 함수

In [52]:
## round(numpy , 소수점 )
arr = np.array([1.5 , -2.33 , 3.457 , -4.095])
print(np.round(arr,2)) # 2번째 자리 까지 반환

[ 1.5  -2.33  3.46 -4.1 ]


In [53]:
## ceil 소수점 올림한 값을 변환
print(np.ceil(arr))

[ 2. -2.  4. -4.]


In [54]:
## floor 소수점을 내림한 값을 반환
print(np.floor(arr))

[ 1. -3.  3. -5.]


In [55]:
## trunc
print(np.trunc(arr))

[ 1. -2.  3. -4.]


## 서로 다른 객체 범용 함수

In [56]:
arr_1 = np.arange(5)
arr_2 = np.arange(1,10 , step = 2)

In [57]:
arr_add1 = np.add(arr_1 , arr_2)

In [58]:
arr_add1

array([ 1,  4,  7, 10, 13])

In [59]:
arr_add2 = arr_1 + arr_2

In [60]:
arr_add2

array([ 1,  4,  7, 10, 13])

In [64]:
arr_subtract_1 = np.subtract(arr_1 , arr_add2)

In [65]:
arr_subtract_1

array([-1, -3, -5, -7, -9])

In [67]:
arr_subtract_2 = arr_1 - arr_add2

In [68]:
arr_subtract_2

array([-1, -3, -5, -7, -9])

In [69]:
arr_multiply = np.multiply(arr_1 , arr_add2)

In [70]:
arr_multiply

array([ 0,  4, 14, 30, 52])

In [71]:
arr_multiply2 = arr_1 * arr_add2

In [72]:
arr_multiply2

array([ 0,  4, 14, 30, 52])

In [73]:
arr_divide_1 = np.divide(arr_1 , arr_2)

In [74]:
arr_divide_1

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [75]:
arr_divide_2 = arr_1 / arr_2

In [77]:
arr_divide_2

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [78]:
arr_mod_1 = np.mod(arr_1 , arr_2)

In [79]:
arr_mod_1

array([0, 1, 2, 3, 4])

In [80]:
arr_mod_2 = arr_1%arr_2

In [81]:
arr_mod_2

array([0, 1, 2, 3, 4])