In [1]:
# import
import numpy as np

## 1d - array

In [3]:
# 1d-array 생성
np1 = np.array([1,3,5,7,9]) # 리스트 객체를 1차원 배열로
np1

array([1, 3, 5, 7, 9])

In [4]:
# 문자열 객체
np2 = np.array('dateedu')
np2

array('dateedu', dtype='<U7')

In [5]:
# arange  = range
np3 = np.arange(7)
np3 # 0 ~ n-1 까지의 수가 리턴 된다

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
# arange 변형
np4 = np.arange(1,6,0.5) # 1 ~ 6 미만까지 0.5 단위로 끊어서 리턴 -> 참고로 range 는 소수점 단위 split 이 안된다.
np4 # start , end , split

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [8]:
# ones  -> 함수 안에 매개변수 길이만큼 1로 채우기
np5 = np.ones(5)
np5


array([1., 1., 1., 1., 1.])

In [10]:
# zeros  -> 전부다 0으로 채우기
np6 = np.zeros(6)
np6

array([0., 0., 0., 0., 0., 0.])

In [12]:
# full shape 을 value 로 채우기
np7 = np.full(5,4.)
np7

array([4., 4., 4., 4., 4.])

In [13]:
# 위해 numpy 들 타입 확인
print(np1.dtype)
print(np2.dtype)
print(np3.dtype)
print(np4.dtype)
print(np5.dtype)
print(np6.dtype)
print(np7.dtype)

int64
<U7
int64
float64
float64
float64
float64


##2d-array

In [14]:
np8 = np.array([[1,3,5,7,9],[2,4,6,8,10]])
np8

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [21]:
np9 = np.ones((2,5) , dtype = 'int') # dtype 으로 자료형 설정도 가능하다
np9

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np10 = np.zeros((2,5) , dtype = 'int')
np10

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np11 = np.full((2,5) , 5) # shape , 채울 숫자
np11

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [26]:
np12 = np.identity(5) # 대각 성분 1인 행렬을 매개변수의 수만큼 만듬 nxn
np12

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 3d-array

In [27]:
np14 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]]
    ])
np14

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [28]:
np15 = np.ones((3,2,4) , dtype = 'int')
np15

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [30]:
np16 = np.zeros((3,2,4),dtype = 'int')
np16

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [31]:
np17 = np.full((3,2,4) , 5)
np17

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

## 배열 정보 확인

In [32]:
## shape = numpy 배열 모양 확인
print(np17.shape)

(3, 2, 4)


In [34]:
##size = 전체 데이터 수 3*2*4 = 24
print(np17.size)

24


In [35]:
## dtype = 데이터 타입의 정보
print(np17.dtype)

int64


In [36]:
## ndim  = numpy 의 차원
print(np17.ndim)

3
