In [4]:
from sklearn.metrics import confusion_matrix

y_true = [0,0,0,1,1,1]
y_pred = [0,1,0,1,1,1]

In [6]:
print(confusion_matrix(y_true , y_pred))

[[2 1]
 [0 3]]


In [7]:
## TP = 2 (0 = 0 의 개수) / FP = 1 (0 = 1 개수) / FN = 0 (1 = 0) / TP = 3 (1=1 의개수)

In [8]:
y_true = [0,0,0,1,1,2,2,2,2]
y_pred = [0,1,1,1,0,0,1,2,2]

print(confusion_matrix(y_true , y_pred))

[[1 2 0]
 [1 1 0]
 [1 1 2]]


In [10]:
from sklearn.metrics import accuracy_score , recall_score , precision_score,f1_score


In [11]:
'''
accuracy_score = 정확도 = (TP+TN) / (TP+FP+FN+TN)
precision_score = 정밀도 = TP / (TP+FP) True 라고 예측 한것 중에 True 인거
recall_score = 재현율 = TP/(TP+FN) 실제가 True 인것중에 True 인거
f1_score = 2 *(precision * recall) / (precision+recall)
'''
y_true = [0,0,0,1,1,1]
y_pred = [0,1,0,1,1,1]

print(accuracy_score(y_true , y_pred))
print(precision_score(y_true , y_pred))
print(recall_score(y_true , y_pred))
print(f1_score(y_true,y_pred))

0.8333333333333334
0.75
1.0
0.8571428571428571


In [12]:
from sklearn.metrics import roc_curve , auc

y_true = [0,0,0,1,1,1]
y_score = [0.1,0.75,0.35,0.92,0.81,0.68]

fpr , tpr , thresholds = roc_curve(y_true , y_score)

## fpr = 거짓 긍정률 / tpr = 참 긍정률

AUC = auc(fpr , tpr)
print(AUC)

0.888888888888889


In [14]:
## 예측 지표 (회귀)

from sklearn.metrics import mean_squared_error , mean_absolute_error , mean_absolute_percentage_error

import numpy as np
np.random.seed(123)

y_true = np.random.random_sample(5)
print(y_true)

y_pred = np.random.random_sample(5)
print(y_pred)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
[0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]


In [19]:
## MSE = 편차 제곱의 평균 / RMSE = 편차 제곱의 제곱근
print(mean_squared_error(y_true , y_pred))
print((mean_squared_error(y_true , y_pred)) ** 0.5) ## RMSE

0.17581754220802784
0.41930602453104326


In [16]:
## MAE = 편차 의 절댓값
print(mean_absolute_error(y_true , y_pred))


0.36474003862364796


In [18]:
## MAPE = 평균 절대 백분율 오차
print(mean_absolute_percentage_error(y_true , y_pred))

1.0843148337483364
