## 수치형 변수 변환하기
주어진 데이터에서 20세 이상인 데이터를 추출하고 'f1'컬럼을 결측치를 최빈값으로 채운 후, f1 컬럼의 여-존슨과 박스콕스 변환 값을 구하고, 두 값의 차이를 절대값으로 구한다음 모두 더해 소수점 둘째 자리까지 출력(반올림)하시오


## 박스 콕스 변환 (Box-Cox 변환)
- 양수값이 나 0을 포함한 변수를 정규분포에 가깝게 만들기 위해서 사용하는 통계적인 방법이다.

## 여존슨 변환
- 박스 콕스 변환에 확장판으로 음수까지 포함한 데이터를 정규분포에 가깝게 만들기 위한 방법이다.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import power_transform

In [81]:
df = pd.read_csv('/content/drive/MyDrive/빅데이터 분석기사/data/box-cox/basic1.csv')

In [82]:
df

id    age city    f1  f2   f3    f4         f5
0    id01    2.0   서울   NaN   0  NaN  ENFJ  91.297791
1    id02    9.0   서울  70.0   1  NaN  ENFJ  60.339826
2    id03   27.0   서울  61.0   1  NaN  ISTJ  17.252986
3    id04   75.0   서울   NaN   2  NaN  INFP  52.667078
4    id05   24.0   서울  85.0   2  NaN  ISFJ  29.269869
..    ...    ...  ...   ...  ..  ...   ...        ...
95   id96   92.0   경기  53.0   1  NaN  ENTJ  52.667078
96   id97  100.0   경기   NaN   0  NaN  INFP  67.886373
97   id98   39.0   경기  58.0   2  NaN  INFP  98.429899
98   id99    1.0   경기  47.0   0  NaN  ESFJ  97.381034
99  id100   47.0   경기  53.0   0  vip  ESFP  33.308999

[100 rows x 8 columns]

In [83]:
# 20세 이상 데이터를 추출
df = df.loc[df['age'] >= 20 , :]

In [84]:
df['age'].unique()

array([ 27. ,  75. ,  24. ,  22. ,  36.3,  38. ,  95. ,  40. ,  20. ,
        77. ,  68. ,  74. ,  41. ,  53. ,  90. ,  34. ,  80. ,  55. ,
        37. ,  86. ,  25. ,  47. ,  65. ,  30. , 100. ,  87. ,  56. ,
        81. ,  23. ,  44. ,  97. ,  93. ,  34.6,  36. ,  52. ,  59. ,
        64. ,  88. ,  43. ,  26.5,  66. ,  35. ,  45. ,  63. ,  71. ,
        92. ,  67. ,  48. ,  73. ,  83.6,  89. ,  54. ,  21.8,  84. ,
        39. ])

In [85]:
# f1 데이터 확인하기
f1_value_counts = df['f1'].value_counts()

In [86]:
f1_value_counts.index[idx]

50.0

In [87]:
idx = f1_value_counts.argmax()
mode_num = f1_value_counts.index[idx]
mode_num

50.0

In [88]:
# f1 컬럼 결측치 채우기
df['f1'].fillna(mode_num , inplace = True)

<ipython-input-88-a5aeb463b495>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f1'].fillna(mode_num , inplace = True)


In [89]:
f1_list = df['f1'].to_list()
f1_list = np.reshape(f1_list , newshape = (-1,1))

In [97]:

yeo_johnson = power_transform(f1_list , method = 'yeo-johnson' ,standardize=False)
box_cox = power_transform(f1_list , method = 'box-cox',standardize=False)

In [98]:
(yeo_johnson , box_cox)

(array([[20.58342293],
        [17.96808139],
        [25.77374532],
        [19.65316692],
        [20.35291527],
        [28.94633478],
        [23.46920513],
        [22.1615116 ],
        [17.96808139],
        [17.96808139],
        [21.93968883],
        [25.77374532],
        [17.96808139],
        [26.18117078],
        [17.96808139],
        [17.96808139],
        [23.68347014],
        [16.45689683],
        [17.96808139],
        [19.65316692],
        [20.35291527],
        [13.76667161],
        [24.10901147],
        [21.26713339],
        [27.58191838],
        [17.96808139],
        [17.96808139],
        [24.10901147],
        [17.96808139],
        [17.96808139],
        [17.96808139],
        [23.68347014],
        [19.17949163],
        [17.47176655],
        [20.35291527],
        [17.96808139],
        [26.383645  ],
        [17.96808139],
        [23.68347014],
        [26.383645  ],
        [24.32032248],
        [17.96808139],
        [25.15621673],
        [17

In [99]:
sum_ = np.abs(yeo_johnson - box_cox)

In [100]:
sum_

array([[0.48366659],
       [0.33718192],
       [0.78393488],
       [0.43120606],
       [0.47062981],
       [0.97381035],
       [0.64901619],
       [0.57359401],
       [0.33718192],
       [0.33718192],
       [0.56088171],
       [0.78393488],
       [0.33718192],
       [0.80805232],
       [0.33718192],
       [0.33718192],
       [0.66145257],
       [0.25389464],
       [0.33718192],
       [0.43120606],
       [0.47062981],
       [0.10763186],
       [0.68621742],
       [0.52248244],
       [0.8915708 ],
       [0.33718192],
       [0.33718192],
       [0.68621742],
       [0.33718192],
       [0.33718192],
       [0.33718192],
       [0.66145257],
       [0.40464733],
       [0.30972509],
       [0.47062981],
       [0.33718192],
       [0.82006716],
       [0.33718192],
       [0.66145257],
       [0.82006716],
       [0.6985473 ],
       [0.33718192],
       [0.7475317 ],
       [0.33718192],
       [0.33718192],
       [0.50959166],
       [0.33718192],
       [0.337

In [101]:
sum_ = np.sum(sum_)

In [102]:
sum_

39.17385668640293

In [103]:
print(np.round(sum_ ,2))

39.17
